spring.application.name=pchy
server.port=8000

spring.datasource.url=jdbc:mysql://pichy-danieljuarezs200523-7eda.c.aivencloud.com:28570/pchy?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_jtNymF5DQoB_6M6UvvC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pichyowo9@gmail.com
spring.mail.password=xtzjyahmottkqpjw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

pchy.uploads.ruta=${user.home}/pchy-uploads/perfiles/
pchy.uploads.url=/uploads/perfiles/

pchy.base-url=https://p-chy.onrender.com